agent_name: memeooorr
author: dvilela
version: 0.1.0
license: Apache-2.0
description: An agent that deploys memecoins.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeid4555nbqrben3bbz62jsycrtssy5mqso4w23q7bjorln3qur7baq
fingerprint_ignore_patterns: []
connections:
- valory/ipfs:0.1.0:bafybeiamz23olgtow4wqf7zpsfnfzf7pxiognrxl2mhn5kvqutlwhgukxa
- valory/abci:0.1.0:bafybeigy6k2d4i4p2vsgz5fcq4vhfq2dd3qewrarvkzbkdlu46mgr7uvz4
- valory/http_client:0.23.0:bafybeid5ffvg76ejjoese7brj5ji3lx66cu7p2ixfwflpo6rgofkypfd7y
- valory/ledger:0.19.0:bafybeibdsjmy4w2eyilbqc7yzutopl65qpeyspxwz7mjvirr52twhjlf5y
- valory/p2p_libp2p_client:0.1.0:bafybeic6ayusdwy4dks75njwk32ac7ur7salgllwf4fdc34ue5z2k5iz4q
- dvilela/twikit:0.1.0:bafybeifvuk57umzfj7epjjpaw7s27wyc4gewpjp6zrszdyfijcmbjmarju
- dvilela/mirror_db:0.1.0:bafybeifhl7e5odr53pbz2bog3tysyyfnimrz2acksgnal4yza4faxam6pa
- dvilela/kv_store:0.1.0:bafybeiecnl7yc5qx6x4q7467i66ehmfw4qydnnry7tjs7plqeytb6ueyvu
- valory/http_server:0.22.0:bafybeic3jpkum7g6qo6x6vdrmvvhj7vqw7ec2op72uc3yfhmnlp5hn3joy
- dvilela/genai:0.1.0:bafybeihp6t4y7mynitwj3afwet2lr5ittrqmk4hop7ycmgyyx3nqkc5sty
contracts:
- valory/gnosis_safe:0.1.0:bafybeicint4o6qwf4z2a6hykufxrm6qmtblydzt34lbhxr2mxma454blo4
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeifxmvucumhcatd5ckz6ugvfwnmjtorhu6e2wdi6onstylw3mradq4
- valory/multisend:0.1.0:bafybeig5byt5urg2d2bsecufxe5ql7f4mezg3mekfleeh32nmuusx66p4y
- dvilela/meme_factory:0.1.0:bafybeibu6j4s4uiwkbtd7qgf4co4dkbiei44ke6gwr4r24skhaufmo3xyq
- dvilela/service_registry:0.1.0:bafybeia4y7jmxbbr6xrthjwjp2vnwluunmdhefsxpkbt6mu4y7uzna7obe
- valory/staking_token:0.1.0:bafybeic2m4oisdcnydyb3ra3r2xgh5ann3gargn2cfsl6o6viehhdxe7ri
- valory/staking_activity_checker:0.1.0:bafybeifcghzfjqx6o2iytyrjjadjqembh6cq3eezfcp7wes3xr7xppmhu4
protocols:
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- valory/abci:0.1.0:bafybeiatodhboj6a3p35x4f4b342lzk6ckxpud23awnqbxwjeon3k5y36u
- valory/acn:1.1.0:bafybeic6h55ov5lrzbah6fate54c4u6spopcexxspw3abotbmffabfddeu
- valory/contract_api:1.0.0:bafybeid247uig2ekykdumh7ewhp2cdq7rchaeqjj6e7urx35zfpdl5zrn4
- valory/http:1.0.0:bafybeih4azmfwtamdbkhztkm4xitep3gx6tfdnoz6tvllmaqnhu3klejfa
- valory/ipfs:0.1.0:bafybeifi2nri7sprmkez4rqzwb4lnu6peoy3bax5k6asf6k5ms7kmjpmkq
- valory/ledger_api:1.0.0:bafybeihmqzcbj6t7vxz2aehd5726ofnzsfjs5cwlf42ro4tn6i34cbfrc4
- valory/tendermint:0.1.0:bafybeigydrbfrlmr4f7shbtqx44kvmbg22im27mxdap2e3m5tkti6t445y
- valory/srr:0.1.0:bafybeihrixgptxuqpf2s4nujypwlv5aed2nboozq5kl4c26cxw6r7si2x4
- dvilela/kv_store:0.1.0:bafybeihimf5f37uupxmugvagmaxworgmz7cxuqpikkyzlgldtbq46jbvci
skills:
- valory/abstract_abci:0.1.0:bafybeihligouknh2v2o2xwugm7yfiypllokbahnxgsh36mgdascvchjmpe
- valory/abstract_round_abci:0.1.0:bafybeiezhbsm2ctlw7frt53jxpdq6d5cq2xaruzsedg66nqmi4prrglame
- valory/termination_abci:0.1.0:bafybeif7lxvscvrsbr6f74ymbb5t3apnfwjxzvwmtixyy7hclpx2pqa3oa
- valory/transaction_settlement_abci:0.1.0:bafybeidfhgtyvsltd6naqrifycbobb7nlqk2gtnjvtolbli3okqovdm2su
- valory/registration_abci:0.1.0:bafybeigrxf2uhudr4ode6p77jikrjzfemfttqhoqez366qugqdckbb6wzi
- valory/reset_pause_abci:0.1.0:bafybeid5tsasmon5gennzigr3ffkctz3womegogkhqcatdb6g7l7llwfu4
- dvilela/memeooorr_abci:0.1.0:bafybeia5hrx4z4qq3sekmfsj2l4zasdb4jjzaxb5vpqb5ennigppydnxae
- dvilela/memeooorr_chained_abci:0.1.0:bafybeidbuohkobhz5xxolukilgmaf655ecl24p6puhtqm2i2oicrnkgtoq
- valory/mech_interact_abci:0.1.0:bafybeigvou76l53vtfoff6tf46v3shupybkxsxxeixhsyleg7uughfxin4
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.65.0
default_connection: null
---
public_id: dvilela/kv_store:0.1.0
type: connection
config:
  store_path: ${str:null}
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: dvilela/memeooorr_chained_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    base:
      address: ${str:http://localhost:8545}
      chain_id: ${int:8453}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
      gas_price_strategies: &id001
        gas_station:
          gas_price_api_key: null
          gas_price_strategy: fast
        eip1559:
          max_gas_fast: 1500
          fee_history_blocks: 10
          fee_history_percentile: 5
          default_priority_fee: ${int:30000000}
          fallback_estimate:
            maxFeePerGas: ${int:20000000000}
            maxPriorityFeePerGas: ${int:3000000000}
            baseFee: null
          priority_fee_increase_boundary: ${int:200}
    celo:
      address: ${str:http://localhost:8545}
      chain_id: ${int:42220}
      poa_chain: ${bool:true}
      default_gas_price_strategy: ${str:eip1559}
      gas_price_strategies: *id001
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
---
public_id: dvilela/memeooorr_chained_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/logs}
  params:
    args:
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      reset_pause_duration: ${int:30}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:2}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: memeooorr
      service_registry_address: ${str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      setup:
        all_participants: ${list:["0x8426B9F3e3E6d8ec2E83391CE3Db9Dec69570234"]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      use_termination: ${bool:false}
      tx_timeout: 10.0
      validate_timeout: 1205
      finalize_timeout: 60.0
      history_check_timeout: 1205
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      multisend_batch_size: ${int:50}
      ipfs_address: ${str:https://gateway.autonolas.tech/ipfs/}
      default_chain_id: ${str:base}
      termination_from_block: ${int:21629820}
      minimum_gas_balance: ${float:0.00005}
      min_feedback_replies: ${int:10}
      meme_factory_address_base: ${str:0x82a9c823332518c32a0c0edc050ef00934cf04d4}
      meme_factory_address_celo: ${str:0xeea5f1e202dc43607273d54101ff8b58fb008a99}
      meme_factory_deployment_block_base: ${int:23540622}
      meme_factory_deployment_block_celo: ${int:29323752}
      olas_token_address_base: ${str:0x54330d28ca3357F294334BDC454a032e7f353416}
      olas_token_address_celo: ${str:0xaCFfAe8e57Ec6E394Eb1b41939A8CF7892DbDc51}
      persona: ${str:a cat lover that is crazy about all-things cats.}
      home_chain_id: ${str:BASE}
      twitter_username: ${str:null}
      service_registry_address_base: ${str:0x3C1fF68f5aa342D296d4DEe4Bb1cACCA912D95fE}
      service_registry_address_celo: ${str:0xE3607b00E75f6405248323A9417ff6b39B244b50}
      meme_subgraph_url: ${str:https://agentsfun-indexer-production.up.railway.app}
      skip_engagement: ${bool:false}
      min_summon_amount_base: ${float:0.01}
      max_summon_amount_base: ${float:0.02}
      max_heart_amount_base: ${float:0.0002}
      min_summon_amount_celo: ${float:10.0}
      max_summon_amount_celo: ${float:20.0}
      max_heart_amount_celo: ${float:0.2}
      staking_token_contract_address: ${str:0x0000000000000000000000000000000000000000}
      activity_checker_contract_address: ${str:0x0000000000000000000000000000000000000000}
      alternative_model_for_tweets: ${dict:{"use":false,"url":"https://api.fireworks.ai/inference/v1/chat/completions","api_key":null,"model":"accounts/sentientfoundation/models/dobby-unhinged-llama-3-3-70b-new","max_tokens":16384,"top_p":1,"top_k":40,"presence_penalty":0,"frequency_penalty":0,"temperature":0.6}}
      fireworks_api_key: ${str:null}
      tx_loop_breaker_count: 3
      tools_for_mech: ${dict:{}}
      mech_contract_address: ${str:0xe535D7AcDEeD905dddcb5443f41980436833cA2B}
      mech_chain_id: base
      mech_interaction_sleep_time: 10
      use_mech_marketplace: true
      mech_marketplace_config:
        mech_marketplace_address: '0xf24eE42edA0fc9b33B7D41B06Ee8ccD2Ef7C5020'
        priority_mech_address: '0xe535D7AcDEeD905dddcb5443f41980436833cA2B'
        priority_mech_staking_instance_address: '0xe535D7AcDEeD905dddcb5443f41980436833cA2B'
        priority_mech_service_id: 0
        requester_staking_instance_address: '0xe535D7AcDEeD905dddcb5443f41980436833cA2B'
        response_timeout: 300
      use_acn_for_delivers: false
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: ${str:0.0.0.0}
  port: ${int:8833}
  target_skill_id: dvilela/memeooorr_chained_abci:0.1.0
---
public_id: dvilela/genai:0.1.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  genai_api_key: ${str:null}
---
public_id: dvilela/twikit:0.1.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  twikit_username: ${str:null}
  twikit_email: ${str:null}
  twikit_password: ${str:null}
  twikit_cookies: ${str:null}
  twikit_disable_tweets: ${bool:false}
  twikit_skip_connection: ${bool:false}
  store_path: ${str:null}
---
public_id: dvilela/mirror_db:0.1.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  mirror_db_base_url: ${str:https://afmdb.autonolas.tech}
